### ISSUE TITLE
Fish support

### ISSUE THREAD

**Issue by manuel-uberti** [cantino/mcfly#10]
This looks awesome, and admittedly this is more of a question than an issue per se. :smile: 

Any plans to add support for [Fish shell](https://fishshell.com/)?

**Comment by jurriaan** [comment]
Fish support would be great, fish already has somewhat smarter history (also taking into account the current directory for example). Hopefully mcfly can improve on top of this :)

**Comment by cantino** [comment]
I'm very supportive of someone working on this!

**Comment by WuShichao** [comment]
Please support fish.

**Comment by manuel-uberti** [comment]
@cantino I am closing this. I'm not good enough at Fish scripting to extend `mcfly`. If support for Fish will be added in the future, I'll be there. :)

**Comment by cantino** [comment]
I think we can re-open it to track the issue in case someone else wants to work on it.

**Comment by cantino** [comment]
Work moved to #89.
