### ISSUE TITLE
McFly makes noise when user moves a folder.

### ISSUE THREAD

**Issue by gwk** [cantino/mcfly#12]
This just happened, and seems undesirable. I moved a folder and McFly prints a pointless message.
```
gwk ~/work/pdfminer3/test master*%> $ mv crypto/ decrypt
McFly: Command database paths renamed from /Users/gwk/work/pdfminer3/test/crypto to /Users/gwk/work/pdfminer3/test/decrypt (affected 0 commands)
```

**Comment by cantino** [comment]
Good point. That should be a debug message only, I'll work on it.

**Comment by cantino** [comment]
Fix released in https://github.com/cantino/mcfly/releases/tag/v0.2.4
