### ISSUE TITLE
History lost after using mcfly

### ISSUE THREAD

**Issue by utdrmac** [cantino/mcfly#120]
Repeatable:
1. Open iTerm2
2. Run some command (cd, less, etc)
3. press up arrow to go back through history as far as you want.
3. ctrl-r to open mcfly
4. search for something. press tab exit mcfly with command on cli
5. execute, or ctrl-c the line
6. press up arrow to scroll back through history
7. bell dings because history is gone. cannot up arrow.

$ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)

$ mcfly --version
McFly 0.5.2

**Comment by cantino** [comment]
Thanks @utdrmac! Could you try 0.5.3?

**Comment by utdrmac** [comment]
@cantino 

```
$ brew upgrade mcfly
Warning: cantino/mcfly/mcfly v0.5.2 already installed
```

**Comment by cantino** [comment]
Did you do `brew update` first?

**Comment by utdrmac** [comment]
Seems not. Thought that was automatic. I have 0.5.3 now. Seems to be fixed. Thanks!

**Comment by cantino** [comment]
Awesome, I'm glad it's fixed! I thought brew did that too— odd.
