### ISSUE TITLE
Failed to init for bash

### ISSUE THREAD

**Issue by ChenhuiZhang** [cantino/mcfly#128]
After I run "brew install mcfly", I got this:

ONE MORE STEP!

Add the following to the end of your ~/.bashrc, ~/.zshrc, or ~/.config/fish/config.fish file.

Bash:
  eval "$(mcfly init bash)"

Zsh:
  eval "$(mcfly init zsh)"

Fish:
  mcfly init fish | source
  mcfly_key_bindings
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/mcfly/v0.5.3: 3 files, 5.0MB, built in 1 second

Then I run mclfy init bash, it report below error:

chenhuiz@pccng2484z17:~$ eval "$(mcfly init bash)"
error: Found argument 'init' which wasn't expected, or isn't valid in this context

USAGE:
    mcfly [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help

So does anyone know what is wrong?

**Comment by b3nj5m1n** [comment]
You're running an outdated version.

**Comment by cantino** [comment]
Sorry, I’ll push the new version to homebrew shortly.

**Comment by cantino** [comment]
Released: https://github.com/cantino/mcfly/releases/tag/v0.5.4

**Comment by ChenhuiZhang** [comment]
Thanks! Now it works.

**Comment by cantino** [comment]
Great!

**Comment by jmlucjav** [comment]
hi,

I just installed in WSL in windows 10, with the install script, and I get something very similar, anyone knows what's up?

```
error: Found argument 'is' which wasn't expected, or isn't valid in this context

USAGE:
    mcfly [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help
```

thanks
