### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by mshron** [cantino/mcfly#13]
Really enjoying mcfly, thanks for making it!

With the Solarized Light color scheme, all of the un-highlighted suggestions are invisible (see attached images).

<img width="521" alt="screenshot 2018-12-04 10 01 18" src="https://user-images.githubusercontent.com/454998/49451763-e1882900-f7ad-11e8-8866-6e897f85551a.png">
<img width="521" alt="screenshot 2018-12-04 10 00 59" src="https://user-images.githubusercontent.com/454998/49451755-ddf4a200-f7ad-11e8-9f4e-36807890c31c.png">

If this isn't a priority for you, I'd be happy to hack on it some time.

I poked a bit through `interface.rs` and `settings.rs`. From a cursory examination, seems like one way to add a light mode would be for `settings.rs` to look for an environment variable (`MCFLY_LIGHT`?) around [here](https://github.com/cantino/mcfly/blob/ac83f3b837acb5baacb8800ad1898ba9a9c0884e/src/settings.rs#L163), set a bool in settings, and then for `menubar()` `prompt()` and `results()` to act accordingly. Would that be your preferred way of propagating a setting like that?

**Comment by cantino** [comment]
Glad you like it! Yes, I realized after releasing that I'd only tested on my dark terminals! Oops! 🙄It'd be great to have your help on this, and your suggested method is reasonable. Another option would be to variabilize the colors used [here](https://github.com/cantino/mcfly/blob/master/src/interface.rs#L118), [here](https://github.com/cantino/mcfly/blob/master/src/interface.rs#L176), and [here](https://github.com/cantino/mcfly/blob/master/src/interface.rs#L51) and allow them to be passed in somehow.

**Comment by bmhenry** [comment]
Depending on how complicated you want to make this, pointing a variable or a config file towards the output shell script generated by pywal or wpgtk and grabbing the foreground color from that would be an awesome option. 
I don't think there's any option supported by the majority of terminal emulators for getting the current foreground color, unfortunately.

**Comment by cantino** [comment]
@mshron, I think we could start with a simple toggle between light and dark mode, like you suggested. Do you want to work on this, or should I do it?

**Comment by mshron** [comment]
@cantino No preference on my end. If it's not something that you wanted to make a priority, I'd be happy to work on it (probably one evening next week). But if you'd like to do it, definitely don't let me stand in your way!

**Comment by cantino** [comment]
I'd be a big fan of having you as an OSS contributor, so I'll let you give it a shot. 😄 If you get stuck or can't find the time, let me know and I'll try to get it done.

**Comment by mshron** [comment]
👍 Sounds good to me

**Comment by mshron** [comment]
Okay, I've got the basic logic working. Now just to figure out a good color scheme 😄

**Comment by cantino** [comment]
Nice!

**Comment by DivineOmega** [comment]
The ability to change theme colours will be great. I've been trying to use mcfly in the default dark terminal that's integrated into PHP Storm, and unfortunately most of the text is not visible at all, making it very difficult to use.

**Comment by mshron** [comment]
@DivineOmega I don't think the light mode PR will fix your problem, but it might point the way to including a more comprehensive set of color choices.

**Comment by cantino** [comment]
Merged in https://github.com/cantino/mcfly/commit/5be3eb8ba0122cafb7540c3750bb5ffd3aecbea6 and deployed in 0.3.0, thanks!!

**Comment by cantino** [comment]
@mshron One issue: it looks like we lost the highlight color as you use the arrow keys. I'll try to add it back in.

**Comment by cantino** [comment]
Fixed in b7edc7db1197f8b32f105aa9504ce4911f5569bb
