### ISSUE TITLE
Deleting all items causes unwrap panic

### ISSUE THREAD

**Issue by hayd** [cantino/mcfly#130]
This is an edge case from a new machine with no commands (!) yet run, but also reproducible if you F2 delete every command... upon pressing ctrl+R:
```
❱ thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidColumnType(0, Null)', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.15.0/src/row.rs:149:31
```
Once I run a command then ctrl+R runs without panic.

expectation: either errors with a message saying "no commands in history" or show the empty list.

**Comment by cantino** [comment]
Thanks!
