### ISSUE TITLE
mcfly_prompt_command:14: no such file or directory: mcfly is home/.cargo/bin/mcfly

### ISSUE THREAD

**Issue by areThereAnyUserNamesLeft** [cantino/mcfly#133]
Not an issue with mcfly -  but it took me a while to debug and it might help others or stop further questions.

```mcfly_prompt_command:14: no such file or directory: mcfly is home/.cargo/bin/mcfly```

This message occurred on zsh.

**The cause was an alias I had for the `which` command that was causing it's output to equal `mcfly is home/.cargo/bin/mcfly` rather than the path.**

I was almost writing a PR until I realised the bug was my shell config 😄 .

Removing the alias solved the issue.

Thanks for mcfly - I'm looking forward to using it

**Comment by areThereAnyUserNamesLeft** [comment]
Closing as thought it may help others with the same issue.

**Comment by cantino** [comment]
Thanks for documenting this!
