### ISSUE TITLE
Not working in Tmux at startup

### ISSUE THREAD

**Issue by g4570n** [cantino/mcfly#135]
Hi, I have updated Mcfly to the latest version and I have changed the code in `.bashrc` to: `eval "$(mcfly init bash)"` , this works without problems in individual terminals, but when I am open tmux or I open a new pane inside, I get this message:

`-bash: mcfly: the order was not found`

if I do use `ctrl-r` it doesn't start mcfly. To make it works I have to do manually: `. ~/.bashrc` , and so mcfly works again if I do `ctrl-r`

is there any way to avoid this behavior in `tmux`?

**Comment by cantino** [comment]
Hey @g4570n. That's a very strange error message.  Does everything work fine with the older source `source "/usr/local/opt/mcfly/mcfly.bash"` form?

**Comment by g4570n** [comment]
If I'm try with:

```
if [[ -r ~/bin/mcfly.bash ]]; then
  source ~/bin/mcfly.bash
fi
#eval "$(mcfly init bash)"
```

I am get this error in tmux:
"Cannot find the mcfly binary, please make sure that mcfly is in your path before sourcing mcfly.bash."

Both `mcfly` and `mcfly.bash` are in `~/bin/`

**Comment by cantino** [comment]
And I assume `~/bin/` is in your `$PATH`?

**Comment by g4570n** [comment]
> And I assume `~/bin/` is in your `$PATH`?

Yes, 

```
$ echo $PATH
/home/g4570n/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by cantino** [comment]
So I assume you can type `mcfly --version` and it works because it's in your path. Is it possible that the PATH is being setup after the lines where you source ~/bin/mcfly.bash?

**Comment by g4570n** [comment]
> So I assume you can type `mcfly --version` and it works because it's in your path. 

Yes, it works.

```
$ mcfly --version
McFly 0.5.5
```

> Is it possible that the PATH is being setup after the lines where you source ~/bin/mcfly.bash?

The PATH setting is in my `.profile` file:

```
# if running bash                                                                    
if [ -n "$BASH_VERSION" ]; then                                                      
    # include .bashrc if it exists                                                   
    if [ -f "$HOME/.bashrc" ]; then                                                  
    . "$HOME/.bashrc"                                                                
    fi                                                                               
fi                                                                                   
                                                                                     
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then                                                         
    PATH="$HOME/bin:$PATH"                                                           
fi 
```

**Comment by g4570n** [comment]
Wow, after sending you the answer I realized what you say, I changed the order and now it works xD

Thanks!

```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi
```

**Comment by cantino** [comment]
Great, I’m glad it’s working!
