### ISSUE TITLE
Can't install via Brewfile

### ISSUE THREAD

**Issue by cmer** [cantino/mcfly#147]
As you know, Homebrew expects the Github repo to be called `username/homebrew-package`. To around this, you advise to tap as such: `brew tap cantino/mcfly https://github.com/cantino/mcfly`.

However, in Brewfile, we cannot specify a URL for taps, which makes it impossible to automate the installation of McFly with a Brewfile.

**Comment by cmer** [comment]
I have created a separate repo that solves this problem. Would you consider "adopting" my repo as the official way to install McFly with Homebrew? 

https://github.com/cmer/homebrew-mcfly

**Comment by cantino** [comment]
Hey @cmer, thanks, I didn't realize this. Are you okay if I copy the pattern to my username?

**Comment by cmer** [comment]
Of course. Steal the whole thing!

**Comment by cmer** [comment]
Which, I stole from you, by the way. 😂

**Comment by cantino** [comment]
Thanks!

**Comment by cantino** [comment]
What does the Brewfile line look like for the repo named `cantino/homebrew-mcfly`?

**Comment by cmer** [comment]
```tap 'cantino/mcfly'
brew 'mcfly'```

**Comment by cantino** [comment]
So `tap 'cantino/mcfly'` implies a request to `cantino/homebrew-mcfly`, I gather.

**Comment by cmer** [comment]
Correct.

**Comment by cantino** [comment]
Okay, this is done! I'm keeping it in both places so the old style of install works too.
