### ISSUE TITLE
Add Ctrl-j/k movement bindings

### ISSUE THREAD

**Issue by tversteeg** [cantino/mcfly#16]
I would like to be able to use Ctrl-j and Ctrl-k to move up and down, similar to the movement keys in FZF. Would this be possible?

**Comment by greyblake** [comment]
In bash `Ctrl-r` actually allows to move with up and down with `Ctrl-n` (next) and `Ctrl-p` (previous).

**Comment by halhenke** [comment]
Theres nothing essential to bash about any of those keybindings - they are just defaults that can be rebound - `bind -p` will show the current setup.

**Comment by cantino** [comment]
`ctrl-n` and `ctrl-p` have been added (and will be pushed out in the next release).

If someone wants to work on more general key binding support as a contribution, I'd be open to it.

**Comment by cantino** [comment]
Update v0.2.5 pushed.
