### ISSUE TITLE
Provide musl build 

### ISSUE THREAD

**Issue by jminh** [cantino/mcfly#161]
Is it also feasible to provide a musl build?

Current mcfly-v0.5.6-x86_64-unknown-linux-gnu.tar.gz build cannot run on a
CentOS 7 machine due to the glibc issue.

```
./mcfly
./mcfly: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./mcfly)
```

**Comment by cantino** [comment]
@praveenperera is this an easy change with the new GitHub Actions setup?

**Comment by praveenperera** [comment]
@jminh a musl build will be created when the next version is released

**Comment by praveenperera** [comment]
@jminh musl build is now available
