### ISSUE TITLE
[Feature request] Place interface at the bottom of the terminal

### ISSUE THREAD

**Issue by Tagussan** [cantino/mcfly#174]
Hi,
Since prompt are flowing from top to the bottom, users' eyes are always at the bottom of the terminal; however, if I execute mcfly by `Ctrl-R`, the input and suggestions are displayed at the top of the terminal, which forces user to move the gaze from the bottom to the top of the terminal temporarily. I think if mcfly can place everything on the bottom, the eye movement will be reduced and this tool will be more convenient. Of course, I love current mcfly, which helps me a lot every day :)

Thanks,

**Comment by agrism** [comment]
Hi @Tagussan do you mean this way?

<img width="300" alt="mcfy-bottom-menu" src="https://user-images.githubusercontent.com/33702214/127738908-c5ec0f1d-57d7-4f76-8852-06602e9ee8ba.png">

or all content as it is now should be moved to bottom?

**Comment by Tagussan** [comment]
Hi @agrism ,
Thanks for your suggestion! That style reduces eye movement, but I think it would reduce eye movement more if we can place like this:
- Reverse the order of suggested history; The best likely command user want for the context should come at the bottom
- Place the blue bar at the bottom and place the input area above it; I feel it would be more comfortable if the typed command and the suggested history (most likely one) are placed closer.

![new](https://user-images.githubusercontent.com/3764516/127741490-4a319452-ae8f-454e-aafc-02a021935040.PNG)

**Comment by cantino** [comment]
Closed by #180! Thanks @agrism!

**Comment by Tagussan** [comment]
Thank you for your implementation, @agrism! I tested new release, and this is exactly what I wanted :)
