### ISSUE TITLE
How to get McFly to list history in frecency or recency?

### ISSUE THREAD

**Issue by wyuenho** [cantino/mcfly#177]
Sometimes I just want to trigger McFly to look up the last 1 or 2 or 3 command, especially when they are long, but there doesn't seem to a way to do that in McFly, the completion list just uses some unknown heuristics to sort the list. Is there anyway to adjust that?

**Comment by jerm** [comment]
Came here to request this.  Actually went back to regular ctrl-r because of the difficulty of access to recent commands :(

**Comment by cantino** [comment]
I'd be very open to a pull request that adds a toggle keybinding and an environment variable setting to switch between default ranking and recency ranking.

**Comment by cantino** [comment]
Closed by #179!
