### ISSUE TITLE
Result navigation stopped working in PhpStorm 2021.2 SSH client

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#182]
Invoking McFly works, but pressing Up/Down arrow keys for navigation does nothing. Other keys, like Esc, F2, etc. work.

I've tested, that Up/Down keys work as usual:

* inside bash itself
* when I launch Midnight Commander
* when McFly is disabled and I press Ctrl+R and navigate results

Related PhpStorm issue: https://youtrack.jetbrains.com/issue/IDEA-275189

---

It worked in PhpStorm 2021.1, but stopped working in PhpStorm 2021.2.
McFly versions: 0.5.6, 0.5.8, 0.3.5

**Comment by cantino** [comment]
I don't know why this would be. Something is intercepting the arrow keys, perhaps?

**Comment by aik099** [comment]
I have no idea. The Arrow keys work in Bash itself and in other apps, as I've mentioned, but not in McFly anymore.

Maybe there is a Debug Mode in McFly, that will allow understanding what keycodes PhpStorm's SSH client is passing back to McFly vs ones that it should be passing?

**Comment by aik099** [comment]
Was fixed in PhpStorm 2021.2.1 for me.
