### ISSUE TITLE
Option to change RUN, EDIT, DELETE keys

### ISSUE THREAD

**Issue by hlascelles** [cantino/mcfly#186]
I use mcfly a lot, thank you! One thing I am used to (from alternative history methods) is "ENTER to choose, but not run". I then either ENTER to choose or "double-tap ENTER" to invoke.

Also change `delete` from F2 to DEL.

Would that be possible?

**Comment by hlascelles** [comment]
Here is a working version that I am now using locally as a built binary. It is probably not idiomatic rust, and it has no tests, but you get the idea... https://github.com/hlascelles/mcfly/compare/master...use-editable-keymap

**Comment by cantino** [comment]
I think it'd be nice to eventually support arbitrary keymaps. I'm hesitant to add a one-off option that just remaps a couple keys, though.

**Comment by hlascelles** [comment]
Fair enough... I'll see if my branch eventually expands to cover more!
