### ISSUE TITLE
Is there a support for wild cards

### ISSUE THREAD

**Issue by henioStraszny** [cantino/mcfly#195]
I'd like to be able to use wildcards in my search, like asterix (*) for any. Is that possible?

**Comment by cantino** [comment]
Yes, `%` should work.

**Comment by henioStraszny** [comment]
Thanks @cantino :beer: 

I wasn't able to find that info in documentation.

**Comment by cantino** [comment]
Good point, I just added it to the [Features list](https://github.com/cantino/mcfly/blob/master/README.md#features). Thanks!
