### ISSUE TITLE
Globally set HISTFILE variable with Fish results in fish_history corruption when running a bash subshell

### ISSUE THREAD

**Issue by btglr** [cantino/mcfly#199]
As can be seen in this issue: https://github.com/fish-shell/fish-shell/issues/8349, 'corruption' of the `fish_history` file occurs when using mcfly with Fish.
Due to HISTFILE being set globally with `set -gx`: https://github.com/cantino/mcfly/blob/2daa339f0ee52c5e7b17321c3e64d1fe715d8d6d/mcfly.fish#L12
running `bash` inside a Fish shell using this plugin causes the `bash` shell to inherit the HISTFILE variable which results in it being set to `~/.local/share/fish/fish_history` instead of `~/.bash_history`. Subsequently, bash starts writing in the `fish_history` file which uses a different format and in turn breaks the history until manually fixed.

**Comment by cantino** [comment]
Have you tried to see if `set -x` is sufficient for it to work?

**Comment by cantino** [comment]
As I think about it, this issue is likely to occur whenever you call one shell (without mcfly init code) inside a shell with mcfly init code. Not sure what the best solution is.

**Comment by cantino** [comment]
Do you mind seeing if https://github.com/cantino/mcfly/pull/204 fixes this for you?

**Comment by btglr** [comment]
> Do you mind seeing if #204 fixes this for you?

I just tried it and it does fix the problem.

**Comment by cantino** [comment]
Great, thanks for checking!

**Comment by cantino** [comment]
Released in 0.5.10.
