### ISSUE TITLE
Doesn't show any history prior to install

### ISSUE THREAD

**Issue by JVMartin** [cantino/mcfly#218]
Zsh version:
```
zsh 5.8 (x86_64-ubuntu-linux-gnu)
```

Ubuntu version:
```
Ubuntu 20.04 Focal
```
![image](https://user-images.githubusercontent.com/4450814/148129288-d0d1e5bf-ecc9-4aa4-8f8f-83fb0cfb656d.png)

Top terminal is showing `history | grep kubectl`.

Bottom terminal shows McFly has no knowledge of any pre-existing history prior to its installation, for some unknown reason.

Is there supposed to be somewhere in the instructions where it shows you how to pull in prior history? It doesn't show any history prior to the installation of McFly.

Trying to figure this out on my own, this doesn't work either:
![image](https://user-images.githubusercontent.com/4450814/148130044-8d68c79b-798f-444f-affb-6e555ba4349d.png)

**Comment by cantino** [comment]
Have you customized anything about your zsh history settings? What does `echo $HISTFILE` say, and what is the format?

**Comment by JVMartin** [comment]
@cantino I believe I am using totally default "oh my zsh" installation.

```
jacob@jacob-xps:~ » echo $HISTFILE
/home/jacob/.zsh_history

jacob@jacob-xps:~ » head $HISTFILE                                                                                                                                                                           3:06 PM
: 1583258324:0;nb materialize-lists
: 1583258448:0;kubectl logs email-platform-scheduler-5d66ffbf96-zkzgr
: 1583258789:0;kubectl logs email-platform-scheduler-5d66ffbf96-2j6s8
: 1583258895:0;kubectl describe pod email-platform-api-5c5b97b7d4-7gspf
: 1583271893:0;history | grep find | grep "ts"
: 1583272995:0;nb domain-index
: 1583273122:0;nb domains-index
: 1583274773:0;git reset staging
: 1583278938:0;kubectl get logs flux-dc695b985-tcbtb
```

**Comment by cantino** [comment]
It's possible that #221 will fix this.

**Comment by cantino** [comment]
You could try updating to the latest release and deleting the `~/.mcfly` directory and see if that helps.

**Comment by JVMartin** [comment]
Just installed latest version `0.5.12` and still am unable to see any of my history :cry:

**Comment by JVMartin** [comment]
Oops, I'm a dumbass and neglected the `rm -rf ~/.mcfly` piece - after doing that, I see my history! Yay! Thank you. :pray:

**Comment by cantino** [comment]
I'm glad it's fixed for you!
