### ISSUE TITLE
Feature Request - Use VIM key bindings to navigate results

### ISSUE THREAD

**Issue by aindriu80** [cantino/mcfly#227]
Hi,

I have started using McFly and it has been great, searching through my history is so much easier! 

I have a request though, is it possible to bind the VIM navigation keys to navigate up and down the search results instead of using the cursor keys? I currently use ZSH and in my` .zshrc` file I have the following which remaps the letters `k` and `j` to jump into command mode (instead of pressing Escape) where I can move around quickly in the terminal - pressing` i `escapes back into Edit mode.

`bindkey -M viins kj vi-cmd-mode`

It would be great to be able to jump into Command mode, select a search result and go back into insert mode

**Comment by cantino** [comment]
Good idea!

**Comment by ikey4u** [comment]
any progress or plan?

**Comment by cantino** [comment]
Yes, this has been implemented for a while. :)
