### ISSUE TITLE
Support zsh

### ISSUE THREAD

**Issue by shanghai-Jerry** [cantino/mcfly#23]
/usr/local/opt/mcfly/mcfly.bash:23: command not found: shopt
/usr/local/opt/mcfly/mcfly.bash:47: command not found: bind

**Comment by cantino** [comment]
What shell are you using?

**Comment by GaurangTandon** [comment]
Same issue. I was using Zsh, but after looking at #3, I realized mcfly is not ready for Zsh yet.

**Comment by andersonaguiar** [comment]
Same thing here, I'm using zsh.

**Comment by MathieuDoyon** [comment]
Same here

**Comment by shanghai-Jerry** [comment]
> Same thing here, I'm using zsh.

yes, zsh

**Comment by shanghai-Jerry** [comment]
> Indeed, it doesn't currently support zsh.

ok alright, but i can use ctrl-r  to search back commands

**Comment by cantino** [comment]
Consolidating with #3.
