### ISSUE TITLE
Last exit code return 1 - mcfly.bash

### ISSUE THREAD

**Issue by sawaYch** [cantino/mcfly#24]
Seems return exit code 1 when `. ./{path to mcfly.bash}` execute in `.bashrc`
The last exit code 1 disappear if I comment this line in `mcfly.bash` : 
```bash
...
PROMPT_COMMAND="__last_exit=\$?;history -a \$MCFLY_HISTORY;mcfly add -
-exit \$__last_exit --append-to-histfile;history -cr \$MCFLY_HISTORY;$
{PROMPT_COMMAND}"
...
```
...but It _does_ affect the program, myfly can;t save lastest history

**Comment by sawaYch** [comment]
More information:
when I run `${PROMPT_COMMAND}`, it returns:
`__last_exit=$?;history: command not found`

**Comment by sawaYch** [comment]
Okay. I think I misunderstand something.

The error code is always normal exit with 0 actually ( I check with echo $? in each command)

So the problem is that my Powerline theme prompt shown a number with orange label... And I wrongly thought it means last error code, but it isn't. It just means how many child processes running in the background in current shell process.

Maybe I can tweak powerline to ignore print the process count if bg only has mcfly.

I will close this issue.

**Comment by cantino** [comment]
The clobbering should be fixed by 9cf7edf3a303f527517efc26ae478dda4090fb2e in the next release, which I'll try to do today.

But are you using Bash as your shell?

**Comment by sawaYch** [comment]
Thank you. Yes, I am using Bash.

**Comment by cantino** [comment]
v0.2.5 has been pushed.
