### ISSUE TITLE
delete huge mistake

### ISSUE THREAD

**Issue by delanym** [cantino/mcfly#241]
Suppose I accidentally paste a huge wad of text and attempt to run as a command. Previously I would open the history file and delete it manually. How would I do this in mcfly?

**Comment by cantino** [comment]
Search for it in the McFly UI and press F2.

**Comment by delanym** [comment]
It appears I need to use the beginning string, which looks like "./mvnw Caused by" but the search doesn't match anything. Is there some mismatch between the length of a record and the search's ability to bring it up?

![image](https://user-images.githubusercontent.com/5310238/156822501-c88c7997-7dc6-4bb5-bc69-d1fc7a4ea27f.png)

**Comment by cantino** [comment]
It should match anywhere in the string. Are you launching McFly with ctrl-r? That doesn't look like the McFly UI.

**Comment by delanym** [comment]
Yeah im confused. Mcfly replaces ctrl+r, but it doesn't replace the history file or accessing that through the up key - it provides an alternative history.

It still looks like it didn't include the above command. Is that because it failed?

**Comment by cantino** [comment]
That’s possible, perhaps there was an issue logging something so long.
You’re correct that the Up arrow is still managed by the shell’s history
file.
