### ISSUE TITLE
Powershell Support

### ISSUE THREAD

**Issue by owenlamont** [cantino/mcfly#250]
I saw this mentioned on an [earlier issue](https://github.com/cantino/mcfly/issues/106) but was wondering if it would be possible to also support Powershell. I'm completely ignorant of how much effort this would involve or if it is possible at all but I'd love to use mcfly if possible from there.

**Comment by upyesp** [comment]
Checkout the PSReadline PowerShell module, might give you what you want as an interim.

Here's a blog post about it, with a neat config: https://www.hanselman.com/blog/adding-predictive-intellisense-to-my-windows-terminal-powershell-prompt-with-psreadline

**Comment by owenlamont** [comment]
Thanks for the tip, I'll checkout PSReadline

**Comment by cantino** [comment]
I don't use Powershell so I'm not planning to work on it, but I'd accept contributions.

**Comment by torculus** [comment]
Considering that `mcfly` has working Powershell support, maybe we could close this issue now?

**Comment by owenlamont** [comment]
It does!? I had no idea. Keen to try it if so.

**Comment by cantino** [comment]
👍🏼
