### ISSUE TITLE
CTRL+R does not bind to mcfly

### ISSUE THREAD

**Issue by andrewgill-dev** [cantino/mcfly#252]
mcfly was being triggered in zsh on MacOS with CTRL+R and then stopped working the following day triggering the standard reverse search instead.

Running `mcfly search` works as expected

The .zshrc file does not appear to complete running the line `eval "$(mcfly init zsh)"` as lines after this are not triggered, but no error messages are produced.

Version 0.6.0

**Comment by andrewgill-dev** [comment]
Restarted machine and it is working now. Should have tried this first. Closing issue and will see if I can replicate.

**Comment by cantino** [comment]
Glad you figured it out!
