### ISSUE TITLE
McFly broken in VSCode terminal after new shell integration

### ISSUE THREAD

**Issue by agawley** [cantino/mcfly#277]
VSCode just rolled out a new shell integration in the built in terminal. After enabling it (I believe it is now enabled by default BTW) I get a McFly error complaining it can't find the $HISTFILE.

The setting:
`"terminal.integrated.shellIntegration.enabled": true,`

The error:
`McFly: /var/folders/sj/j72mhwmd1dd4_66xkl1pzsn40000gn/T/vscode-zsh/.zsh_history does not exist or is not readable. Please fix this or set HISTFILE to something else before using McFly.`

Changing the setting to `false` makes the error go away, but as I say, I think `true` is the default now

**Comment by cantino** [comment]
Duplicate of https://github.com/cantino/mcfly/issues/273. Since we use a PROMPT_COMMAND (in Bash), VSCode's terminal might not work there. For zsh, I'd think it would work if you set a HISTFILE in the settings? I don't use VSCode, so I'm not sure.

**Comment by agawley** [comment]
Closing in favour of #273

**Comment by migueldemoura** [comment]
@cantino, indeed, just setting `HISTFILE` will do the trick for vscode.
