### ISSUE TITLE
Sorting by time is not sorting by time

### ISSUE THREAD

**Issue by yshui** [cantino/mcfly#282]
Setting sorting to `LAST_RUN`, or use F1 to switch sorting option to "Sort to Time", and the result is not sorted by time.

![a](https://user-images.githubusercontent.com/366851/189336528-12e2fc43-cf91-475a-a00b-b7552d35d7bc.png)

**Comment by yshui** [comment]
I think this is because `MCFLY_FUZZY` is not 0, which I think is a surprising behavior. Sort by time should sort strictly by time.

This happens even when search term is empty, I think fuzziness shouldn't have an effect when no search term is set?

**Comment by navazjm** [comment]
I agree with you. I think sort by time should sort strictly by time. I have created a PR with a fix for this issue
