### ISSUE TITLE
feature request: selecting places on line instead of executing

### ISSUE THREAD

**Issue by samm81** [cantino/mcfly#284]
hi @cantino ! thanks for your work on this, super neat. I know you're only maintaining part time, but I figured I'd throw this out there.

I'd love it if mcfly didn't execute the command when I selected it, but instead placed it on the command line for viewing/editing, allowing me to hit enter and execute it myself once I'd verified/changed it. or for there to be a flag that could turn on this behavior.

thanks again for your work!

**Comment by navazjm** [comment]
@samm81 When you select a command, instead of pressing the enter key, press tab and it should place it on the command line and not execute it

**Comment by samm81** [comment]
yay, awesome! just what I wanted :) this is nowhere in the docs as far as I can tell - perhaps this issue will help others find this functionality :)

**Comment by cantino** [comment]
Glad you like it @samm81! Thanks @navazjm :)
