### ISSUE TITLE
Remote history server

### ISSUE THREAD

**Issue by jmauro** [cantino/mcfly#285]
Hello,

Firstly, thanks for this awesome tools... I was wondering if Mcfly could not be extended to provide some kind of remote server to get the database from (a bit like [atuin](https://github.com/ellie/atuin)). I don't if this is a feature you want to work on.

Kind regards,
JM

**Comment by cantino** [comment]
It should work with a file in Dropbox / another file-system-based synchronization store right now.

It could also be upgraded to make requests to a remote server, but that isn't something that I'm interested in working on personally at the moment.
