### ISSUE TITLE
FR: Option to disable confirmation before deleting command

### ISSUE THREAD

**Issue by pickx** [cantino/mcfly#318]
Either with a setting that simply skips the confirmation, or with a different key binding that deletes without confirmation.

Thanks, and thanks for maintaining this useful software.

**Comment by cantino** [comment]
There's already a command line option delete_without_confirm, so it'd just need to also have a ENV variable like MCFLY_DELETE_WITHOUT_CONFIRM or something that you could set. I'd be open to receiving a PR for this improvement.

**Comment by cantino** [comment]
Wait, that already exists! Use `MCFLY_DELETE_WITHOUT_CONFIRM`.

**Comment by pickx** [comment]
woah, thanks. (should have looked at the code a little better before asking)

kind of funny that you suggested the exact same name, though.
