### ISSUE TITLE
ctrl-r does not work for some zsh environments

### ISSUE THREAD

**Issue by jingzhaoou** [cantino/mcfly#323]
I really like `mcfly` and installed it on all my Ubuntu boxes, some with Ubuntu 18.04 and some with Ubuntu 20.04. A puzzling thing is that after adding `eval "$(mcfly init zsh)"` to my `.zshrc`, some zsh works fine with `ctrl-r` while some does not. When things do not work, the existing zsh `ctrl-r` handling is triggered but not `mcfly`. 

I dumped `mcfly init zsh` output to a file and use `eval "$(cat ${HOME}/mcfly.sh)"` to set up `mcfly`. This allows me to debug things further. I found that for all the cases, the following is executed upon startup. 
```
    zle -N mcfly-history-widget
    bindkey '^R' mcfly-history-widget
 ```
But I don't know why `ctrl-r` works only sometimes. I wonder if anyone has some suggestions how I can debug this issue further. Thanks a lot!

**Comment by mepsteinpear** [comment]
I also had the binding stop working recently in zsh on MacOS Monterey. 

I seemed to have acquired this error when ever I start a new terminal now (not sure it is it related): 
```(eval):30: command not found: shopt
(eval):80: command not found: bind```

Any ideas on how to fix the key binding? 

Thanks!

**Comment by cantino** [comment]
Glad you figured it out @jingzhaoou!

@mepsteinpear, is this a bash vs zsh issue? https://stackoverflow.com/questions/26616003/shopt-command-not-found-in-bashrc-after-shell-updation

**Comment by mepsteinpear** [comment]
I don't think it is a bash issue this is on macOS Monterey installed via homebrew. My issues started after running  `brew upgrade` I tried reinstalling McFly again or to downgrade it in brew but there is only listing for `mcfly` in brew.

**Comment by cantino** [comment]
I'm not sure, sorry.

**Comment by mepsteinpear** [comment]
@cantino as with all things rebooting seemed to fix it 🤷 

thank you for your attention!
🙇
