### ISSUE TITLE
Customize Prompt?

### ISSUE THREAD

**Issue by vedkothavade** [cantino/mcfly#324]
Is it possible to change the `$` prompt to something custom, perhaps through and environment variable? I'd like to have it match my shell prompt. Sorry if this has been asked before, all I could find was something about `PROMPT_COMMAND` but that did not seem to be relevant.

**Comment by cantino** [comment]
Not currently, but I'd accept a PR for this change.

**Comment by vedkothavade** [comment]
Sounds good, I'll take a stab at it soon.

**Comment by vedkothavade** [comment]
@cantino Have you had a chance to check this out yet? No rush, just wondering :)
