### ISSUE TITLE
^R to quickly move cursor by typing first few letter.

### ISSUE THREAD

**Issue by faxotherapy** [cantino/mcfly#328]
Hi, before installing mcfly, I could quickly move my cursor by typing `ctrl` + `R` and the first few letters of, for example, a command argument so that I could quickly modify that specific option. After installing mcfly, I have to use the `alt` key with arrows key to travel to a specific string of the command line, which is somewhat a downgrade. Is it possible to use mcfly while still keeping the original functionalities brought by `ctrl` + `R`. What is now left to quickly move the cursor is the forward cursor move using `ctrl` + `S` key. Thank you.

**Comment by cantino** [comment]
You can't currently change mcfly's key bindings using environment variables, but you could put the output of `mcfly init bash` or `mcfly init zsh` into a file, modify that, and then eval it on statup.

**Comment by faxotherapy** [comment]
ah, indeed. Thanks for the tip.
