### ISSUE TITLE
Feature: quick stats

### ISSUE THREAD

**Issue by nfultz** [cantino/mcfly#330]
It would be neat to add something like `mcfly stats` to the cli for the curious - it could be roughly equivalent to 

    sqlite3 .local/share/mcfly/history.db "select substr(cmd,1,instr(cmd,' ')-1), count(1) as n from commands group by 1 order by 2 desc limit 40;"

Inspired by https://www.miskatonic.org/2023/02/21/commands/

**Comment by cantino** [comment]
I'd be happy to accept a pull request!

**Comment by nfultz** [comment]
Sure, I can add it to my todo list.
