### ISSUE TITLE
Linux Kernel 6.2 issue

### ISSUE THREAD

**Issue by dedguy21** [cantino/mcfly#333]
OS: Arch  Linux
Kernel: 6.2
Shell: Bash, Zsh, & Nushell
Terminal: Kitty & Wezterm
Mcfly ver:  0.7.1

I was updated to kernel 6.2 the other day, I noticed when using mcfly, though I could ctrl-r and make a selection,  that selection wasn't carried through back to the terminal, so it wouldn't execute. Also, selection would not be carried over to be modified either.  I checked the issue across three shells, and two different terminal to be sure.

Rolling back to kernel 6.1 fixed the issue for me. This is more of an FYI in case more people update to kernel 6.2 

I haven't traced root issues beyond rolling back.

**Comment by cantino** [comment]
Thanks @dedguy21. Maybe related to https://github.com/cantino/mcfly/issues/212?

**Comment by dedguy21** [comment]
More than likely, I'll test and get back to you. Thanks.

**Comment by Tealk** [comment]
I have the same behavior, where can I set this "CONFIG_LEGACY_TIOCSTI"?

**Comment by comio** [comment]
> Thanks @dedguy21. Maybe related to #212?

Yes. This bug can be marked as duplicate of #212

**Comment by dedguy21** [comment]
Should I close the issue since it is a repeat of #212?

**Comment by kjozsa** [comment]
I had hit the same issue, also on arch, with kernel `6.2.1-arch1-1`. Is this something what should get fixed in `mcfly` then or in the kernel?

**Comment by somepaulo** [comment]
Just updated to `6.2.2-arch1-1`, issue persists.

**Comment by dedguy21** [comment]
FYI:
An arch maintainer advised me that they are definitely not going to make CONFIG_LEGACY_TIOCSTI available going forward as it poses a potential security risk.

**Comment by kauruus** [comment]
There is [a bug in the kernel](https://lore.kernel.org/lkml/CAFqZXNt84oqHo5aQQbjuroA6fGzMyso9HuN4fz3u1mygze2Yrw@mail.gmail.com/T/) that prevents me to set `dev.tty.legacy_tiocsti`, so I make a [simple kernel module](https://github.com/kauruus/legacy_tiocsti) to re-enable `TIOCSTI`.

**Comment by dedguy21** [comment]
If this works on zsh as long as zsh is the login, then I'll make the switch.

Thanks. I'll close this dup issue.

**Comment by cantino** [comment]
It might be worth leaving this open for other people to find.

**Comment by kjozsa** [comment]
I don't even see how this issue will get resolved. Will `bash` work around the new kernel limitation? Will `mcfly` adapt and change the way bash is being used? Will the kernel come up with something which allows again things to work as intented?

Meanwhile, I made the switch to `fish`, to be able to use the latest kernel while keeping `mcfly` - so far I'm grateful for getting pushed into this direction.

**Comment by a-dekker** [comment]
https://github.com/dvorka/hstr/ is also affected by this, see https://github.com/dvorka/hstr/issues/478.
https://github.com/junegunn/fzf is not affected.

I can confirm using kauruus kernel module does help (https://github.com/cantino/mcfly/issues/333#issuecomment-1455039317).
And in https://github.com/dvorka/hstr/issues/478#issuecomment-1454727507 an attempt is made to fix hstr in a "fzf way".

But so far I did not see McFly having this issue addressed, so in the mean time we need workarounds like the kernel module or alternative tools/shells.

**Comment by comio** [comment]
I suggest this workaround modifying the bind script:
 - Create a temp file
 - Pass the filename to mcfly executable via a proper option
 - Store the search result to the provided  temporary file;
 - source the file and update READLINE_LINE variable accordantly
 - Remove the temporary file

McFly should support a special option to pass and store the search result.

my 2EurCents.

ciao

luigi

**Comment by a-dekker** [comment]
The bug that the parameter CONFIG_LEGACY_TIOCSTI cannot be set has been fixed in recent 6.2 kernel releases https://github.com/dvorka/hstr/issues/478#issuecomment-1467633404

**Comment by dedguy21** [comment]
> The bug that the parameter CONFIG_LEGACY_TIOCSTI cannot be set has been fixed in recent 6.2 kernel releases [dvorka/hstr#478 (comment)](https://github.com/dvorka/hstr/issues/478#issuecomment-1467633404)

I ran the "# sysctl -w dev.tty.legacy_tiocsti=1 " and it works, but rookie question, where do we put the command so we don't have to run it manually every start up?

Not /etc/environment, and the local .bash_profile doesn't have permisson either. What is a good way to automate the process without getting permission failures?

**Comment by darthShadow** [comment]
Any sysctl parameters generally go in a custom file in `/etc/sysctl.d`

**Comment by dedguy21** [comment]
> Any sysctl parameters generally go in a custom file in `/etc/sysctl.d`

Works like a charm. Thanks 🙏

**Comment by jkseppan** [comment]
> I suggest this workaround modifying the bind script:
> 
> * Create a temp file
> * Pass the filename to mcfly executable via a proper option
> * Store the search result to the provided  temporary file;
> * source the file and update READLINE_LINE variable accordantly
> * Remove the temporary file

Here's a patch that implements something like this, but only for replacing the edit buffer. What I couldn't get to work was running the command properly. You could insert it into history with `history -s`, echo the prompt and command to make it look like you ran it, and write it into a file and source the file, but even then any error status returned by the command does not get conveyed to the shell. I guess this is because it gets called through a readline binding, so it looks to the shell like an editing operation instead of executing a command.

There are various hacks in the answers for [this Unix & Linux Stackexchange question](https://unix.stackexchange.com/q/213799/90804) that might be adapted. Personally I'm fine with pressing Enter another time after choosing the command.

[mcfly.bash.patch](https://github.com/cantino/mcfly/files/11133010/mcfly.bash.patch)

**Comment by dedguy21** [comment]
@RHOOPH 

You should have a directory:
/etc/sysctl.d/

In that directory is where you save your file.

Example:

vim 10_legacy_tiocsti.conf

Then write

legacy_tiocsti=1 in the file

Save to /etc/sysctl.d/10_legacy_tiocsti.conf

**Comment by somepaulo** [comment]
> Then write
> 
> legacy_tiocsti=1 in the file

This should read `dev.tty.legacy_tiocsti=1` actually.

**Comment by Dlinuigh** [comment]
> @somepaulo for somereason, /etc/sysctl.d seems doesn't work on new kernel 6.3.x, are they dropping it? Manual set using
> 
> ```
> sudo sysctl -w dev.tty.legacy_tiocsti=1
> ```
> 
> Still work, but not the boot .conf file.
> 
> any idea why ? Or it's specific to fedora only?

Work on arch, with kernel 6.8.1.

**Comment by cantino** [comment]
I'm open to PRs that fix this if anyone sees a path forward.

**Comment by cantino** [comment]
It'd be great if bash users could test https://github.com/cantino/mcfly/pull/416

**Comment by digikata** [comment]
building and using #416 works for me on a linux 6.8 kernel that was broken w/ bash on the stable release.

**Comment by cantino** [comment]
Should hopefully be fixed by https://github.com/cantino/mcfly/pull/416 and https://github.com/cantino/mcfly/releases/tag/v0.9.0.

**Comment by cantino** [comment]
I believe this is fixed! Please re-open if not.
