### ISSUE TITLE
ZSH error -- Possibly related to issue #313/315 but the workaround didn't fix my Issue

### ISSUE THREAD

**Issue by dedguy21** [cantino/mcfly#338]
OS: Arch
Kernel: 6.2
Shell: zsh
Term: Wezterm, kitty

Update 3: Sorry, coming from bash where things are a bit simpler to setup. I had to setup a zle env before I could then bindkey mcfly-history-widget with no error.
...........................................................................................................................

Update 2: Ok well, running as RUST_BACKTRACE=full mcfly search, fixes the issue.
..........................................................................................................................

Update:

I'm getting the following error now after rebooting: 
❯ RUST_BACKTRACE=1 mcfly search        
thread 'main' panicked at 'McFly error: "/tmp/mcfly.7tsNRDnd" file not found', src/shell_history.rs:17:45
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
...................................................................................................................

Hi. I switched from bash to zsh due to kernel 6.2 and the "CONFIG_LEGACY_TIOCSTI" issue. 

Now in zsh after creating a .zsh_history file, Mcfly give the following error McFly: /home/dedguy21/.zsh_history does not exist or is not readable. Please fix this or set HISTFILE to something else before using McFly.

I followed issue #313/#315 for resolution but even after commenting out and replacing to eval "$(cat ~/mcfly-debug.zsh)"  and copy and past the zsh script to mcfly-debug.zsh, I'm still getting the above error for zsh, which is now the default shell.

**Comment by dedguy21** [comment]
I'll close this issue out in a week, just in case someone else has similar issue moving from bash to zsh with mcfly.,

**Comment by cantino** [comment]
Did you get this figured out?

**Comment by dedguy21** [comment]
Yes, I got it figured out and running without issues. 

But moved back to bash, now that the work around is in place.
