### ISSUE TITLE
Mcfly not working on Fedora / KDE anymore

### ISSUE THREAD

**Issue by Tegomena** [cantino/mcfly#344]
On Fedora 37 with KDE 5.27.3, using Konsole 22.12.3 and mcfly version 0.8, its not possible to execute a command listed via mcfly (return key), nor is it possible to edit a command via TAB.

**Comment by cantino** [comment]
Maybe this? https://github.com/cantino/mcfly/issues/333

**Comment by kajdo** [comment]
same with fedora 37 server ... guess @cantino is right

**Comment by cantino** [comment]
This is in bash, I assume?

**Comment by Tegomena** [comment]
Thanks, the command solves the problem on Fedora 37:

sysctl -w dev.tty.legacy_tiocsti=1
