### ISSUE TITLE
Fish’s private mode

### ISSUE THREAD

**Issue by Aeron** [cantino/mcfly#354]
The question is simple: should McFly automatically respect Fish’s private mode? Because, at this point, it doesn’t, so anything you type in private mode goes to MyFly’s database, while Fish’s history stays clear of it.

The fix is simple since there’s an environment variable for that. Yet an emphasis here is on automatically. Should a user consciously decide to forbid and manually implement it in the config, or should it be enabled by default?

I’ll gladly implement the default option if the community agrees to it.

**Comment by cantino** [comment]
I wasn't aware of Fish's private mode. That's a great question. If fish's history avoids recording commands in private mode, we probably should too. I'd be glad to accept a PR.

**Comment by Aeron** [comment]
Got it. I’ll get to it then 👍
