### ISSUE TITLE
how can dont show this bar

### ISSUE THREAD

**Issue by newyorkthink** [cantino/mcfly#359]
![image](https://user-images.githubusercontent.com/87791643/236853745-5ce46771-1b15-4c54-a39a-1979a4aa002a.png)
![image](https://user-images.githubusercontent.com/87791643/236853852-9158d976-810d-4411-8627-faaf4b4ae778.png)
i set it not work

**Comment by cantino** [comment]
You're correct, this is currently broken. https://github.com/cantino/mcfly/pull/363 should fix it.
