### ISSUE TITLE
Typing to console does not work

### ISSUE THREAD

**Issue by thran** [cantino/mcfly#360]
From some moment mcfly stopped writing to console, i.e. I can search history but it is not run on select and I even cannot edit command.

For split second I see error from this line: https://github.com/cantino/mcfly/blob/master/src/fake_typer.rs#L14

I suspect it is not fault of mclfy, but I have no idea what is the problem with my linux bash (on other machines it works well). 
Please advise.

**Comment by somepaulo** [comment]
You probably have kernel 6.2 or newer on this machine.
See #333

**Comment by thran** [comment]
Duplicate of #333
