### ISSUE TITLE
mcfly stopped working (kernel issue)

### ISSUE THREAD

**Issue by hferreiro** [cantino/mcfly#371]
Since some time ago, I cannot get mcfly to work. After running its UI with ctrl-r, pressing enter or tab on any row just goes back to bash with an empty prompt.

I tried emptying my .bashrc or running `mcfly -d search` directly without success. Is there any way to debug this issue?

**Comment by cantino** [comment]
Does `mcfly --version` give output? And I assume you have `eval "$(mcfly init bash)"` in your bashrc?

**Comment by yingmanwumen** [comment]
I got the same mistake, and this is my bash and mcfly versions:
bash: 5.2.15
mcfly: 0.8.1

**Comment by yingmanwumen** [comment]
this issue would help:
https://github.com/dvorka/hstr/issues/478

**Comment by hferreiro** [comment]
> Does `mcfly --version` give output? And I assume you have `eval "$(mcfly init bash)"` in your bashrc?

Yes, it's initialized as that. Running `mcfly` works, what's not working is selecting something in its UI.

**Comment by hferreiro** [comment]
> this issue would help: [dvorka/hstr#478](https://github.com/dvorka/hstr/issues/478)

I can confirm this is the issue. The workaround at https://github.com/dvorka/hstr/issues/478#issuecomment-1616417044 is working for me:
```
$ sysctl -w dev.tty.legacy_tiocsti=1
```

**Comment by yingmanwumen** [comment]
@cantino `hstr` is going to fix the same issue in the next release: https://github.com/dvorka/hstr/issues/486. Would mcfly fix this?

**Comment by cantino** [comment]
If someone wants to work on this, I'd be happy to accept a fix. Does setting `READLINE_LINE` have the same effect as using tiocsti?

**Comment by koutsie** [comment]
> 

+1 for the fix, odd!

**Comment by grantcarthew** [comment]
Fresh install of EndeavourOS, same issue:
- GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
- mcfly 0.8.1

**Comment by KAGEYAM4** [comment]
`$ sysctl -w dev.tty.legacy_tiocsti=1` do we still have to use this?  Also does it need to be turned off when we git a fix in mcfly?

```
Kernel: 6.7.4-zen1-1-zen
```

**Comment by grantcarthew** [comment]
> `$ sysctl -w dev.tty.legacy_tiocsti=1` do we still have to use this? Also does it need to be turned off when we git a fix in mcfly?
> 
> ```
> Kernel: 6.7.4-zen1-1-zen
> ```

I'm still needing to run this in my terminal to be able to use McFly. The latest Kernel and updates were applied yesterday.

**Comment by yingmanwumen** [comment]
> `$ sysctl -w dev.tty.legacy_tiocsti=1` do we still have to use this? Also does it need to be turned off when we git a fix in mcfly?
> 
> ```
> Kernel: 6.7.4-zen1-1-zen
> ```

I'm using Debian Testing with kernel version `6.6.13-amd64`, and my current `mcfly` of version `0.8.4` just works without any special configuration at all, although the kernel config doesn't set tiocsti:
![image](https://github.com/cantino/mcfly/assets/58961385/5dbbb274-dc95-4016-8d25-bd57b2a615c5)

**Comment by waja** [comment]
For me:
```
❯ uname -r
6.8.0-76060800daily20240311-generic
❯ cat /boot/config-6.8.0-76060800daily20240311-generic | rg TIOCSTI
# CONFIG_LEGACY_TIOCSTI is not set
❯ source /etc/os-release ; echo $VERSION
22.04.4 LTS (Jammy Jellyfish)
```

it is needed to set `dev.tty.legacy_tiocsti=1`, to work around this issue.

**Comment by grantcarthew** [comment]
This works on Arch (EndeavourOS) to make the fix survive a reboot:

```shell
echo "dev.tty.legacy_tiocsti=1" | sudo tee -a "/etc/sysctl.d/custom.conf"
```

**Comment by cantino** [comment]
Confirmed this is https://github.com/cantino/mcfly/issues/333

**Comment by Daniel15** [comment]
Is there a workaround for systems where you don't have root access?

**Comment by cantino** [comment]
Closed, this is https://github.com/cantino/mcfly/issues/333.
