### ISSUE TITLE
feature request - CLI option to dump the sqlite3 db 

### ISSUE THREAD

**Issue by Houlistonm** [cantino/mcfly#372]
Use case: Go back after a long shell session and extract the commands run to convert to an automated process:

I currently make a copy of my command db, and run commands to find a block of commands that I've run since "yesterday" or some other time range and filter using sql to output to a file.

Feature request:
Add a `dump` option to `mcfly` to print all `cmd` from the `commands` table in chronological ascending order.

Addition arguments: 
- `--before=<TIME>`
- `--since=<TIME>`
- `--rc=0`
- `--sort=[ASC|DESC]`
- `--regex=[what ever regex family is supported]`

**Comment by cantino** [comment]
Cool idea. I'd be open to a PR that adds a command for this.

**Comment by TD-Sky** [comment]
- What is the format of the time? RFC3339?
- Should we accept shorter format like 2023, 2023-08 etc?
- Would it be better to use `--time=<TIME>` where `<TIME>` could be `..`, `..=` or `<single-value>`?

**Comment by TD-Sky** [comment]
I've got the time parser ready: [chrono-systemd-time-ng](https://github.com/TD-Sky/chrono-systemd-time-ng). I will publish the crate after implementing this request in mcfly with it.

---

@Houlistonm what is argument `--rc`?

**Comment by cantino** [comment]
#374 has been merged and will be released shortly!
