### ISSUE TITLE
Temp file creation issue on start

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#38]
When attempt to make temp file in `mcfly.bash` is made it ends up with this error:

```
mktemp: cannot create temp file /tmp/mcfly.XXXX: Invalid argument
```

Googling a bit showed, that adding more `X` to the temp file creation command solves the problem.

I'm using Slackware Linux x64.

**Comment by cantino** [comment]
How many Xs did you need?

**Comment by aik099** [comment]
For me it worked with 6 Xs, but I've added ended up using 8 Xs (double of Xs count used currently) just in case. Maybe that entropy factor is somehow dependent on used OS.

**Comment by cantino** [comment]
Thanks for letting me know. I'll change it to `export MCFLY_HISTORY=$(mktemp -t mcfly.XXXXXXXX)`. I assume this is what you ended up with?

**Comment by aik099** [comment]
Exactly.
