### ISSUE TITLE
mcfly prints arguments when moving files around

### ISSUE THREAD

**Issue by NRGDEAD** [cantino/mcfly#389]
Hi there,

when mcfly is active and I move a file around via `mv`, it prints the filenames. Interestingly including a trailing semicolon if one was added to the command.

```
Skynet:pts/2:nrg:ram $ mkdir a z;
Skynet:pts/2:nrg:ram $ mv a z;
a
z;
```

It does not do that, when I add another command:
```
Skynet:pts/2:nrg:ram $ mv z/a . && echo foobar;
foobar
```

`mv` is not aliased to anything. But I just had this happen as well:
```
Skynet:pts/2:nrg:ram $ /usr/bin/mv z/a .
Skynet:pts/2:nrg:ram $ /usr/bin/mv a z
Skynet:pts/2:nrg:ram $ mv z/a .
z/a
.
/mnt/ram/z/a
/mnt/ram/a
```

I am using ZSH on Arch (btw). This is how I init mcfly:
```
if which mcfly > /dev/null; then
        export MCFLY_DELETE_WITHOUT_CONFIRM=true
        export MCFLY_INTERFACE_VIEW=BOTTOM
        export MCFLY_KEY_SCHEME=vim;
        #export MCFLY_PROMPT=">"
        export MCFLY_RESULTS=100;
        eval "$(mcfly init zsh)";
fi;
```

Is this expected? Might it have something to do with #12?
Personally, I'd prefer there to be no output when none is expected, as that usually means everything went well. ;-)
If you need any info from me on this, or if I can do anything else, please let me know!

Cheers
NRG

**Comment by cantino** [comment]
Thank you for this report @NRGDEAD. This was indeed introduced by a recent change and will be fixed shortly.

**Comment by cantino** [comment]
Released a fix, thanks!
