### ISSUE TITLE
zsh-vi-mode conflict

### ISSUE THREAD

**Issue by sohaiberrabii** [cantino/mcfly#395]
Not sure if there is a clean way of handling the priority of '^R' binding. 
But I had to explicitly comment out  https://github.com/jeffreytse/zsh-vi-mode/blob/master/zsh-vi-mode.zsh#L3471

**Comment by unexist** [comment]
Oh wow, I had this issue for weeks and never checked the zsh-vi-mode file for another binding of ^R!

McFly didn't bind on initial start and I had to re-source the config on every new shell.
