### ISSUE TITLE
F3 key does not work with 'vim' key scheme

### ISSUE THREAD

**Issue by gevorg-vardanyan-im** [cantino/mcfly#399]
Hi all,
thanks for awesome project.

There is an issue related to key scheme,
if I enable vim key scheme on my zsh or bash config file
```
$ export MCFLY_KEY_SCHEME=vim
```
vim keys work, but F3 does not, it does not toggle location between 'All directories' and 'This directory'.
With no 'MCFLY_KEY_SCHEME' if works.

Additional info:
I use Ubuntu 22,
tilix terminal multiplexer,
the issue is actual for bash and zsh.

Thanks in advance.

**Comment by cantino** [comment]
Good catch, thanks @gevorg-vardanyan-im. Should be fixed in ea0e7a9 and released soonish.
