### ISSUE TITLE
Permissions error on startup

### ISSUE THREAD

**Issue by gwk** [cantino/mcfly#4]
Hi, I just installed mcfly to try it out on macOS 10.14.2 (beta 18C52a). I opened a new shell, and saw the "reading history for the first time" message. I closed that shell and opened another, and saw this message:

```
-bash: /var/folders/kb/bswbcrr56ld5cv7zzhyp57gr0000gn/T/mcfly.XXXX.qqMnwGRv: cannot overwrite existing file
```

If I remove the file, and open another shell, I get a message with a similar file name. When I `ls -l` the permissions string is `-rw-------` for the file, and `drwx------@ 254 gwk  staff  8128 Dec  3 19:02 T` for the parent `T` directory. Any ideas?

**Comment by cantino** [comment]
Weird! Thanks for testing out McFly. I'm still on 10.13.6. Do both terminal windows have the same value for `$MCFLY_HISTORY`? Does running `mktemp -t mcfly.XXXX` twice give you the same output? (It shouldn't.)

**Comment by gwk** [comment]
Every time I open a window it creates a new `mcfly.XXXX`, which matches the set `$MCFLY_HISTORY`. If I run the `mktemp` command above twice I get different paths.

```
Last login: Mon Dec  3 19:15:05 on ttys011
-bash: /var/folders/kb/bswbcrr56ld5cv7zzhyp57gr0000gn/T/mcfly.XXXX.SNQglCSU: cannot overwrite existing file
gwk ~ $ echo $MCFLY_HISTORY
/var/folders/kb/bswbcrr56ld5cv7zzhyp57gr0000gn/T/mcfly.XXXX.SNQglCSU
gwk ~ $ 
```

**Comment by cantino** [comment]
That's very odd. If you edit `mcfly.bash` and add after line 9:

```bash
chmod 644 $MCFLY_HISTORY
```

Does that help at all? I can't tell if `mcfly.bash` is erring out on line 8 or if it's later.

**Comment by cantino** [comment]
I believe that this has been fixed.
