### ISSUE TITLE
Automatic Bash completion inclusion with Homebrew

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#40]
Homebrew is able to automatically enable completion for installed packages without need to add below code to `~/.bashrc` file:

```bash
if [[ -r "$(brew --prefix)/opt/mcfly/mcfly.bash" ]]; then
  source "$(brew --prefix)/opt/mcfly/mcfly.bash"
fi
```

when you have this code in there already (you should have it since it's part of Homebrew installation process):

```bash
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

Theoretically (I'm not creating Homebrew packages usually) adding below line to installation part of Homebrew Formula should do the trick:

```ruby
bash_completion.install "mcfly.bash"
```

Maybe above line should replace `prefix.install "mcfly.bash"` line.

**Comment by cantino** [comment]
That feels like a hack to me since McFly is a lot more than bash completion. I think people should probably opt-in?

**Comment by aik099** [comment]
Actually you're right. I wasn't looking at this topic from that perspective. Yeah, it's better to let user choose when to include the `mcfly.bash` rather then including it in fixed place and protentially getting same problem as I've got in #45.
