### ISSUE TITLE
Bug in mcfly.fish

### ISSUE THREAD

**Issue by manfredlotz** [cantino/mcfly#406]
I am using `mcfly 0.8.4`

`mcfly.fish` here in the repository and so `mcfly init fish` output is buggy.

here
```
...
 function __mcfly_add_command -d 'Add run commands to McFly database' -e fish_postexec
    # Check for the private mode
    test -n "$fish_private_mode"; and return
    # Retain return code of last command before we lose it
    set -l last_status $status
...
```
the value of `last_status` is always 1.  Reason is that `set -l last_status $status` is not the first statemen in function `__mcfly_add_command`

**Comment by cantino** [comment]
I don't use fish but I'm open to a PR to fix this.

**Comment by manfredlotz** [comment]
Ok, will do. Plan for coming weekend when I will have more time doing things.

**Comment by 4t8dd** [comment]
just swapping the first two line will fix this issue.

**Comment by manfredlotz** [comment]
@4t8dd Yes, that is what I mentioned above and what I did.

**Comment by cantino** [comment]
Fixed in https://github.com/cantino/mcfly/pull/414
