### ISSUE TITLE
Question: Reason for initial completion not being empty?

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#41]
When I press `Ctrl+R` for the first time the last command is shown automatically. This is radically different comparing to approach default `Ctrl+R` does, where no command is shown and I have to start typing.

Currently I have to delete suggested command first (one-by-one symbol) and start typing what I actually wanted to see.

Maybe instead it's possible to show list of suggested commands below and by pressing `Down arrow` people then can manually confirm, that they want 1st suggested entry to be used.

Right now I don't have a choice really.

**Comment by cantino** [comment]
It should only be pre-filled with a command if you have started to type on the command line before hitting `Ctrl+R`. Is it doing this even when your prompt is empty?

**Comment by aik099** [comment]
> Is it doing this even when your prompt is empty?

Yes, It's always pre-filled with `mc` command (that is command I run almost each time after starting opening an SSH session to server where McFly is installed):

![2019-02-11_0815](https://user-images.githubusercontent.com/1277526/52548274-5b9fe400-2dd5-11e9-8892-3e6526937fcb.png)

If you explain how you're getting currently typed command (I had no idea what you half type command and then press `Ctrl+R`) when `Ctrl+R` is pressed, then I'll be able to provide you with debug info to identify that problem.

**Comment by aik099** [comment]
Closing in favor of #45, because cause for both issues turned out to be the same.
