### ISSUE TITLE
Windows binaries missing

### ISSUE THREAD

**Issue by thisismygitrepo** [cantino/mcfly#412]
Can we please have Windows binaries included in release?
Thanks

**Comment by cantino** [comment]
@jtschuster or @praveenperera do you know how to do this?

**Comment by jtschuster** [comment]
I'm not familiar with publishing releases, but I can look into it maybe this weekend.

**Comment by cantino** [comment]
Fixed in https://github.com/cantino/mcfly/pull/415, thanks @jtschuster!

**Comment by RamidaKit** [comment]
Missing again

**Comment by cantino** [comment]
Should be there now. https://github.com/cantino/mcfly/releases/tag/v0.9.2
