### ISSUE TITLE
init shell failed?

### ISSUE THREAD

**Issue by 4t8dd** [cantino/mcfly#413]
I use fish shell. But when I execute the initiation and nothing writtent to fish config file.
And when try to dump and there is a panic. But I can search with mcfly.

And also ini bash, nothing written to .bashrc and when I exit bash and return with a dump.
Panics happened too.

Is this a bug or I missed anything?

I installed with brew and my os is Mac m2.

**Comment by cantino** [comment]
Did you add `mcfly init fish | source` to your fish config file?

**Comment by 4t8dd** [comment]
> Did you add `mcfly init fish | source` to your fish config file?

yes, but nothing got written as I inspected.
Something wrong here? But the key bingding works and I can search.

**Comment by 4t8dd** [comment]
should I paste all the init shell to config.fish manually?

**Comment by 4t8dd** [comment]
PR: https://github.com/cantino/mcfly/pull/414

**Comment by cantino** [comment]
Good fix, thank you!
