### ISSUE TITLE
Question：how the Neural Network help mcfly for better performance?

### ISSUE THREAD

**Issue by 4t8dd** [cantino/mcfly#418]
As the readme states the nn would make the mcfly smarter. But I failed to find how. And I got some findings, please correct me if I am wrong. 
1. how the training of NN here benifitical to mcfly?

      Because I did not find how the training result applied to mcfly. The history and settings are passed to trainer by reference. But no data changed in place. Because all the data changed are just copy. I can not tell how this training helps here.

It looks the best_overall_network and best_overall_error are two metrics should be pay attenttion to. But how these take effect.
And I did not find how the network change the search result. 

2. If I missed anythiing with above, how can I evaluate the effect of this NN?

3. For train, why the outer loop run forever without any stop condition?

    with millions of times of internal loop(although I got 786 lines of cache), I saw nothing changed, the best_overall_error and some other metrics. But it just keep going. Or is there other point for a user to break the training?

Not so much experience in rust and NN. Please help provide some feedbacks.

**Comment by cantino** [comment]
It was only trained once on my own data, now it is used to prioritize
results.

**Comment by 4t8dd** [comment]
@cantino Thanks for your reply. But I still did not get it.

> It was only trained once on my own data, now it is used to prioritize results.

would you please point me how it will prioritize the results?
Because as I found  history just use default network and network in train does not updated.


>only trained once your data

Do you mean it will stop after training? or just keep unchanged after some training loops?
Because the out loop is forever in train.

**Comment by cantino** [comment]
Yes, it's a static network, it isn't updated as you use it. It honestly doesn't add a lot but was a way to tune a search algorithm that seems to work fairly well.
