### ISSUE TITLE
Question: Any issues with "HISTCONTROL=ignoreboth"?

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#42]
I have `HISTCONTROL=ignoreboth` (acts as `ignorespace;ignoredups`) in my `.bash_profile` file to avoid seeing same command again and again, when browsing through history using Up/Down arrows when I've executed same command several times.

As I've noticed it that takes priority over `HISTCONTROL=ignorespace` set in `mcfly.bash`.

Would that cause any problems to McFly ability to detect multiple sequential same command execution attempts and therefore increase probability for suggesting that command over other commands?

**Comment by cantino** [comment]
I think this should be fine.
