### ISSUE TITLE
Internal output not removed after closing

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#43]
I have setup 2 line bash prompt, that looks like this (not sure if that causes issue to happen):

![2019-02-09_0945](https://user-images.githubusercontent.com/1277526/52518184-66c90780-2c4f-11e9-8a69-7e345e3ecd98.png)

I then enable McFly by pressing `Ctrl+R` and immediately exit via `Esc`. After that I'm seeing that 2 commands were executed and are displayed on screen:

* `#mcfly:`
* `mcfly search`

![2019-02-09_0946](https://user-images.githubusercontent.com/1277526/52518205-b1e31a80-2c4f-11e9-99cc-a15add03b5e3.png)

Is there any reason for not to removing these commands (e.g. I'm not seeing any extra commands, when using native `Ctrl+R` search)?

Related #44

**Comment by cantino** [comment]
No, I think you're right and we could clean these up.

**Comment by cantino** [comment]
Actually, this issue is the same as https://github.com/cantino/mcfly/issues/18
