### ISSUE TITLE
Unable to get desired command suggested

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#45]
As far as I understand:

1. the McFly is only able to suggest commands that were previously executed
2. new commands are executed outside of McFly and therefore are never added to it's database as being executed from a particular folder (because current folder isn't logged in analyzed `.bash_history` file)
3. since suggestions are given for current folder only, then new commands are never suggested
4. only commands initially found in `.bash_history` file are suggested

At least it happens like this for me. Any idea why I'm experiencing such behavior?

**Comment by cantino** [comment]
This shouldn't be the case. McFly uses a shared Sqlite3 database for all terminals. What new commands are you not seeing entered?

**Comment by aik099** [comment]
The command is `project-composer-patch.sh`:
![2019-02-11_0731](https://user-images.githubusercontent.com/1277526/52547262-2d1f0a80-2dcf-11e9-9ed5-5ee6254cb5f7.png)

When I do `history` command the command is clearly shown:
```
...
 4998  project-composer-patch.sh uxmaster
 4999  mc
 5000  p
 5001  cd project/
...
```

**Comment by aik099** [comment]
Here is why it wasn't working:

1. the `mcfly.bash` (that alters `PROMPT_COMMAND`) is sourced from `.bashrc` file
2. the `.bashrc` file is sourced from `.bash_profile` file (right from the beginning)
3. in the `.bash_profile` file I have `PROMPT_COMMAND` being replaced

As a result McFly was made blind (because `mcfly_prompt_command;` part of `PROMPT_COMMAND` wasn't executing at all) and wasn't able to track currently typed command or context (path) in which command was executed.

I've added `mcfly_prompt_command;` manually to my `PROMPT_COMMAND` and it started working as expected:

1. commands being executed are being tracked in context of current path
2. pressing `Ctrl+R` showed empty initial completion instead of using last executed command

Verdict:

We need to somehow verify correct installation, because likely McFly would fail the same was for people having custom `PROMPT_COMMAND`. Suggesting sourcing of `mcfly.bash` from the end of `.bash_profile` or after `PROMPT_COMMAND` is changed (if ever changed) is also a good idea.

**Comment by cantino** [comment]
You should source `mcfly.bash` at the end of your profile.

**Comment by cantino** [comment]
Added notes in 5e4b837fb0d56b62e4eb2d5d8a88bd2733758ee9

**Comment by aik099** [comment]
> Added notes in [5e4b837](https://github.com/cantino/mcfly/commit/5e4b837fb0d56b62e4eb2d5d8a88bd2733758ee9)

You should have changed `.bashrc` into `.bash_profile` as well. In mentioned commit you've changed position of script inclusion, but file stayed the same and problem remains.

Maybe you should add a note, that if you're overriding `PROMPT_COMMAND`, then `mcfly.bash` inclusion absolutely should go after it.

**Comment by cantino** [comment]
.bashrc vs .bash_profile depends on the operating system. On OS X, at least, it seems to be .bashrc.

**Comment by aik099** [comment]
According to https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc:

* `.bash_profile` is used for interactive shells (OSX Terminal, SSH, etc.)
* `.bashrc` is used for non-interactive shells (xterm)

I've tested it by placing `echo "test"` in `.bashrc` and noticed, that it wasn't displayed during Terminal start. Not sure how you tested `.bashrc` execution.

To consolidate stuff it's recommended to add this to `.bash_profile`, which I've did:

```bash
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
```

That explains reasons why `PROMPT_COMMAND` is replaced in `.bash_profile`.
