### ISSUE TITLE
this app does not get along with Sublime Text 3

### ISSUE THREAD

**Issue by kostyrev** [cantino/mcfly#46]
Please see [this](https://forum.sublimetext.com/t/build-3176-high-cpu-usage-plugin-host/41776) discussion on sublime forum.  
There's a screenshot and explanation.

**Comment by kostyrev** [comment]
it seems it's connected with #32   
Could you please cut new release with the fix in #33?

**Comment by cantino** [comment]
Update complete, thanks for the reminder. I've released v0.3.2. Can you let me know if this fixes the Sublime Text 3 issue?

**Comment by kostyrev** [comment]
something went wrong
```bash
[kostyrev@macbook-pro-15 ~ (minikube:default)]$ md5 ~/Downloads/mcfly-v0.3.2-x86_64-apple-darwin/mcfly
MD5 (/Users/kostyrev/Downloads/mcfly-v0.3.2-x86_64-apple-darwin/mcfly) = 01d5ab95089633f55640b673addd4ead
[kostyrev@macbook-pro-15 ~ (minikube:default)]$ ~/Downloads/mcfly-v0.3.2-x86_64-apple-darwin/mcfly -V
McFly 0.3.1
```

**Comment by cantino** [comment]
Thanks for letting me know, I'll fix the internal version number. That is 0.3.2 though. Does it fix the issue for you?

**Comment by cantino** [comment]
https://github.com/cantino/mcfly/releases/tag/v0.3.3 should fix this.

**Comment by kostyrev** [comment]
Unfortunately is [does not](https://ibb.co/TTRPx80) fix it for me

**Comment by cantino** [comment]
Possibly fixed in 84f0123.

**Comment by cantino** [comment]
@kostyrev, would you be able to confirm if this is fixed?

**Comment by kostyrev** [comment]
I confirm that this bug is fixed

**Comment by cantino** [comment]
Thank you!

**Comment by cantino** [comment]
Released as https://github.com/cantino/mcfly/releases/tag/v0.3.4
