### ISSUE TITLE
Highlight search string in a case-insensitive way

### ISSUE THREAD

**Issue by aik099** [cantino/mcfly#47]
Right now search is done in a case-insensitive way, but in found commands matched fragments are highlighted in respect for case. In this situation it becomes hard to spot in a command why it was found at all.

I'm proposing to use approach from PhpStorm IDE: highlight what's being searched for. As for implementation:

1. lowercase found data to get string offset to highlight
2. apply highlighting based on above found offset, but use original (non-lowercased) found data

---

Example when command is found, but not highlighted:
![2019-02-11_1722](https://user-images.githubusercontent.com/1277526/52572955-b65f2d00-2e21-11e9-985e-f6be3243f705.png)

Example when command is found and is highlighted:
![2019-02-11_1722-1](https://user-images.githubusercontent.com/1277526/52572979-c0812b80-2e21-11e9-9654-00b20c1a827b.png)

**Comment by cantino** [comment]
I agree, this is a change we should make.

**Comment by cantino** [comment]
Any interest in working on this?

**Comment by aik099** [comment]
Sorry, I'm a PHP guy.

**Comment by cantino** [comment]
This is fixed in 339f513.
