### ISSUE TITLE
ARM64/ARMHF Support

### ISSUE THREAD

**Issue by NoxInmortus** [cantino/mcfly#69]
Hello,

Could it be possible to support arm64/armhf plateforms ? I love your work, and I miss mcfly on my raspberries and arm64 virtual instances :(

thanks

**Comment by cantino** [comment]
Good idea, I'll try to add it!

**Comment by screendriver** [comment]
> Good idea, I'll try to add it!

Any news about it? I would also love to use `McFly` on my Raspberry Pi ☺️

**Comment by cantino** [comment]
Mind trying the arm7 / arm build here and see if it works for you? https://github.com/cantino/mcfly/releases/tag/v0.4.1

**Comment by screendriver** [comment]
What should I say? **A.W.E.S.O.M.E.** ❗ Importing shell history for the first time takes a little bit longer on my Raspberry Pi but after that it works like a charm 🥳

**Comment by cantino** [comment]
Awesome indeed, I'm glad it's working! Did you need the arm or arm7 build?

**Comment by screendriver** [comment]
I tried it with the arm7 build on my Raspberry Pi 3+

**Comment by NoxInmortus** [comment]
Hello guys, its seems to works but :
```
thread 'main' panicked at 'McFly error: Please ensure that MCFLY_HISTORY is set (environment variable not found)', src/settings.rs:195:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[48.7'C]root@rpitools:[~]: export MCFLY_HISTORY=/tmp/mcfly
[48.2'C]root@rpitools:[~]: #mcfly: 
[47.6'C]root@rpitools:[~]:  mcfly search
thread 'main' panicked at 'McFly error: "/tmp/mcfly" file not found', src/shell_history.rs:13:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and then had to touch /tmp/mcfly
it seems to miss something, I never had to do that manually before

**Comment by cantino** [comment]
That's odd, has it recurred?

**Comment by NoxInmortus** [comment]
@cantino Occuring on all my rpi, 2B, 3B and 4
@screendriver not occuring for you?

**Comment by screendriver** [comment]
No. McFly is running as expected on my Raspberry Pi 3+ **and** Raspberry Pi 4 🤷

**Comment by cantino** [comment]
Is there anything special about your /tmp?

**Comment by cantino** [comment]
@NoxInmortus, `MCFLY_HISTORY` should be set by mcfly.bash / mcfly.zsh. Are you sourcing those in your startup file?

**Comment by cantino** [comment]
If you run 

```
    export MCFLY_HISTORY=$(mktemp -t mcfly.XXXXXXXX)
    tail -n100 "${HISTFILE}" >| ${MCFLY_HISTORY}
```

does `cat $MCFLY_HISTORY` print some history?

**Comment by NoxInmortus** [comment]
Hello,

My /tmp is a tmps (`tmpfs /tmp tmpfs defaults,noatime,nosuid 0 0`)

Another example with CTRL+R on a rpi4:
```
[61.0'C]root@rpi-simtio:[~]: #mcfly: 
[59.0'C]root@rpi-simtio:[~]:  mcfly search
thread 'main' panicked at 'McFly error: Please ensure that MCFLY_HISTORY is set (environment variable not found)', src/settings.rs:195:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[58.0'C]root@rpi-simtio:[~]: grep mcfly /etc/bash.bashrc 
# mcfly ctrl+r
if [[ -r /usr/local/bin/mcfly.bash ]]; then
          source /usr/local/bin/mcfly.bash
[60.0'C]root@rpi-simtio:[~]: ls /usr/local/bin/mcfly.bash
/usr/local/bin/mcfly.bash
[60.0'C]root@rpi-simtio:[~]: echo $MCFLY_HISTORY

[59.0'C]root@rpi-simtio:[~]: 
```

Yes running manually does work

**Comment by cantino** [comment]
What does `cat $MCFLY_HISTORY` print?

**Comment by NoxInmortus** [comment]
@cantino just logged in a new session :
```
[55.0'C]root@rpi-simtio:[~]: cat $MCFLY_HISTORY




^C
[55.0'C]root@rpi-simtio:[~]: echo $MCFLY_HISTORY

[55.0'C]root@rpi-simtio:[~]: 

```

**Comment by cantino** [comment]
And even if you `source /usr/local/bin/mcfly.bash`, `cat $MCFLY_HISTORY` and `echo $MCFLY_HISTORY` are still blank? If so, what does `echo $__MCFLY_LOADED` say?

**Comment by NoxInmortus** [comment]
Hello @cantino 
```
[57.0'C]root@rpi-simtio:[~]: source /usr/local/bin/mcfly.bash
[57.0'C]root@rpi-simtio:[~]: time cat $MCFLY_HISTORY






^C

real    0m46.561s
user    0m0.004s
sys     0m0.000s
^X[56.0'C]root@rpi-simtio:[~]: time echo $MCFLY_HISTORY


real    0m0.000s
user    0m0.000s
sys     0m0.000s
[57.0'C]root@rpi-simtio:[~]: time echo $__MCFLY_LOADED
loaded

real    0m0.000s
user    0m0.000s
sys     0m0.000s
[57.0'C]root@rpi-simtio:[~]: 

```

**Comment by NoxInmortus** [comment]
Hello, any news?

**Comment by cantino** [comment]
Sorry for the delay. Okay, so it's getting into `mcfly.bash`, since `$__MCFLY_LOADED` is set. Is `$MCFLY_SESSION_ID` set? What about `$MCFLY_PATH`?

`$MCFLY_HISTORY` is populated like this:

```
if [[ ! -f "${MCFLY_HISTORY}" ]]; then
    export MCFLY_HISTORY=$(mktemp -t mcfly.XXXXXXXX)
    tail -n100 "${HISTFILE}" >| ${MCFLY_HISTORY}
fi
```

Does `$(mktemp -t mcfly.XXXXXXXX)` work for you?

**Comment by NoxInmortus** [comment]
@cantino Sorry the delay as well.

it seems it does not.

```
$(mktemp -t mcfly.XXXXXXXX)
-bash: /tmp/mcfly.oMw8UsHx: Permission denied
```

a classic `mktemp` does work though.

think we have the heart of the issue, but can't still understand why yet

**Comment by Vitexus** [comment]
My older build http://repo.vitexsoftware.cz/pool/buster/main/m/mcfly/mcfly_0.5.7_amd64.deb for raspberry 
using this source: https://github.com/PureHTML/mcfly/tree/debianized/debian

**Comment by NoxInmortus** [comment]
Never found the core of my issue, stopped trying to use mcfly on rpi. Closing.
