### ISSUE TITLE
Missing libraries after clean install

### ISSUE THREAD

**Issue by lcustodio** [cantino/mcfly#70]
After installing on 
* Mojave 10.14.6
* zsh
* iTerm2

I'm getting this error:
```
/usr/local/opt/mcfly/mcfly.bash:26: command not found: shopt
/usr/local/opt/mcfly/mcfly.bash:65: command not found: bind
```

**Comment by cantino** [comment]
Hey @lcustodio, I think you may be using zsh instead of bash?

**Comment by lcustodio** [comment]
Yes, I spend some time trying to figure out the missing dependencies and end up finding that `shopt` is part of bash. (https://stackoverflow.com/a/26616150/139637)

Do you want some workaround to make it work with zsh?

**Comment by cantino** [comment]
I don't use zsh, but I'm open to contributions. Discussion is here: https://github.com/cantino/mcfly/issues/3
