### ISSUE TITLE
Alternate Vim keybindings

### ISSUE THREAD

**Issue by JamJar00** [cantino/mcfly#72]
As a fairly frequent Vim user I often find that I open mcfly and immediately try to use `h`/`j`/`k`/`l` to move the cursor up and down. Therefore a nice feature might be alternate key bindings that more closely matches vim:
- `j`/`k` - move up/down
- `i` - enter/exit edit mode
- `ESC` - exit edit mode (and exit mcfly?)
- `q` - exit mcfly?

This would be set with an environment variable:
```
MCFLY_KEYBINDINGS=vim
```

**Comment by cantino** [comment]
Great idea @JamJar00, I'm a fan. Would you be interested in adding this? It shouldn't be too hard.

**Comment by JamJar00** [comment]
Sure!

It's been a few years since I wrote my only few lines of rust but it'll be good to have a go.

Any pointers on wher I should be looking in the code?

**Comment by cantino** [comment]
Awesome! The emacs-style bindings are implemented here: https://github.com/cantino/mcfly/blob/master/src/interface.rs#L279
