### ISSUE TITLE
mcfly does not show recently executed commands

### ISSUE THREAD

**Issue by utdrmac** [cantino/mcfly#88]
I'm not sure if this is an issue with my terminal config or issue with mcfly. I can type a command, execute command, then immediately attempt to search (ctrl-r) for the command _I just executed_ and it's nowhere to be found in mcfly. Why isn't mcfly sorting commands based on most-recently executed? I absolutely love the "context awareness" because some commands I only run from specific directories and those always show up first. But I'm in a different dir now, and I just ran a command, and it's not appearing in mcfly.

**Comment by cantino** [comment]
Hey @utdrmac. Do you not see it, even if you search for the command string itself? Or is it just not on the first page of default results?

**Comment by utdrmac** [comment]
I see it, it's just not #1 on the list. I would expect the command _I just typed_ to be at the top of the list since I'm still in the same directory.

**Comment by cantino** [comment]
That's not how mcfly works. Since you can just hit the up arrow to run the most recent command, mcfly prioritizes commands that are less accessible, but still likely to be relevant. It's algorithm certainly isn't perfect, though.

**Comment by dchatterjee172** [comment]
@cantino just faced a strange issue, the up arrow is somehow showing command prioritized by mcfly, 
```
debajyoti@abs ~/sd (sd)(sd)
git --version
git version 2.27.0
debajyoti@abs ~/sd (sd)(sd)
source ~/.bashrc
```

When I pressed up key I got `source ~/.bashrc` instead of `git --version`

which also comes up when I press ctrl-r
```
McFly | ESC - Exit | ⏎ - Run | TAB - Edit | F2 - Delete

$ source ~/.bashrc

source ~/.bashrc
```

**Comment by cantino** [comment]
Up arrow doesn't interface with mcfly, I think that's a coincidence.
