### ISSUE TITLE
Support multiple and separte user's history

### ISSUE THREAD

**Issue by asdf23** [cantino/mcfly#99]
As a second user on the operating system I should not be able to see (nor share) my history with another user on the system. Currently it seems every user sees every other users's history.

**Comment by cantino** [comment]
It'll be looking at your local `~/.mcfly` database. You should not see anyone else's history.

**Comment by asdf23** [comment]
Huh.. I apologize. I can't seem to reproduce it.  What I did was to login to a graphical interface, then `sudo su`  and `exit` to toggle between root and a user. I also tried `su user2`.  Unless it "sticks" from just from a new installation (I used the manual method after downloading one of the releases). I thought I saw this on another box as well.... 
I'll close the ticket unless/until I determine reproducible steps.
